"use client";

import { createContext, useContext, useEffect, useSyncExternalStore } from "react";
import Image from "next/image";

export type Language = "en" | "km";
type Variables = Record<string, string | number>;

const km: Record<string, string> = {
  "Language": "ភាសា", "Overview": "ទិដ្ឋភាពទូទៅ", "Loans": "ប្រាក់កម្ចី", "Borrowers": "អ្នកខ្ចី", "Payments": "ការទូទាត់", "Settings": "ការកំណត់", "Sign out": "ចាកចេញ", "Personal account": "គណនីផ្ទាល់ខ្លួន",
  "Open navigation": "បើកម៉ឺនុយ", "Close navigation": "បិទម៉ឺនុយ", "People": "មនុស្ស", "See each borrower’s loan exposure and payment totals.": "មើលសមតុល្យប្រាក់កម្ចី និងការទូទាត់សរុបរបស់អ្នកខ្ចីម្នាក់ៗ។", "{active} active of {total} loan(s)": "កំពុងដំណើរការ {active} ក្នុងចំណោម {total} កម្ចី", "Principal left": "ប្រាក់ដើមនៅសល់", "Interest due": "ការប្រាក់ត្រូវបង់", "Total paid": "បានបង់សរុប", "No borrowers yet": "មិនទាន់មានអ្នកខ្ចី", "Borrowers appear here when you create a loan.": "អ្នកខ្ចីនឹងបង្ហាញនៅទីនេះពេលអ្នកបង្កើតកម្ចី។",
  "Ledger": "បញ្ជីប្រតិបត្តិការ", "A complete history of money received and how it was allocated.": "ប្រវត្តិពេញលេញនៃប្រាក់ដែលបានទទួល និងការបែងចែក។", "Total received": "បានទទួលសរុប", "Interest collected": "ការប្រាក់ដែលប្រមូលបាន", "Principal collected": "ប្រាក់ដើមដែលប្រមូលបាន", "Date": "កាលបរិច្ឆេទ", "Loan": "កម្ចី", "Borrower": "អ្នកខ្ចី", "Amount": "ចំនួនទឹកប្រាក់", "Interest": "ការប្រាក់", "Principal": "ប្រាក់ដើម", "Method": "វិធីទូទាត់", "No payments yet": "មិនទាន់មានការទូទាត់", "Recorded loan payments will appear here.": "ការទូទាត់កម្ចីដែលបានកត់ត្រានឹងបង្ហាញនៅទីនេះ។",
  "Configuration": "ការកំណត់រចនាសម្ព័ន្ធ", "Review application conventions, integrations, security and data tools.": "ពិនិត្យការកំណត់ ការតភ្ជាប់ សុវត្ថិភាព និងឧបករណ៍ទិន្នន័យ។", "General": "ទូទៅ", "Current financial display and calculation conventions.": "ការបង្ហាញហិរញ្ញវត្ថុ និងរបៀបគណនាបច្ចុប្បន្ន។", "Currency": "រូបិយប័ណ្ណ", "Date format": "ទម្រង់កាលបរិច្ឆេទ", "Interest model": "គំរូការប្រាក់", "Telegram reminders": "ការរំលឹកតាម Telegram", "Secrets remain protected on the server; only their status is shown.": "ព័ត៌មានសម្ងាត់ត្រូវបានការពារនៅម៉ាស៊ីនមេ ហើយបង្ហាញតែស្ថានភាពប៉ុណ្ណោះ។", "Bot token": "ថូខិនបូត", "Admin chat": "ការជជែកអ្នកគ្រប់គ្រង", "Cron protection": "ការការពារ Cron", "Security": "សុវត្ថិភាព", "Authentication configuration loaded from the deployment environment.": "ការកំណត់ផ្ទៀងផ្ទាត់ត្រូវបានផ្ទុកពីបរិស្ថានដាក់ឱ្យប្រើ។", "Password hash": "លេខសម្ងាត់ដែលបានបំប្លែង", "Session signing": "ហត្ថលេខាសម័យ", "Configured": "បានកំណត់", "Missing": "ខ្វះ", "Plaintext password enabled": "បានបើកលេខសម្ងាត់អត្ថបទធម្មតា", "Remove ADMIN_PASSWORD after confirming the password hash works.": "លុប ADMIN_PASSWORD បន្ទាប់ពីបញ្ជាក់ថា password hash ដំណើរការ។", "Data": "ទិន្នន័យ", "Download a portable snapshot of current operational records.": "ទាញយកច្បាប់ចម្លងនៃទិន្នន័យប្រតិបត្តិការបច្ចុប្បន្ន។", "Export loans and payments": "នាំចេញកម្ចី និងការទូទាត់", "The JSON export includes borrowers, loans and payment history. Store it securely.": "ឯកសារ JSON រួមមានអ្នកខ្ចី កម្ចី និងប្រវត្តិទូទាត់។ សូមរក្សាទុកដោយសុវត្ថិភាព។", "Loading settings…": "កំពុងផ្ទុកការកំណត់…",
  "PRIVATE DASHBOARD": "ផ្ទាំងគ្រប់គ្រងឯកជន", "Welcome back.": "សូមស្វាគមន៍មកវិញ។", "Enter your admin password to manage your loans.": "បញ្ចូលលេខសម្ងាត់អ្នកគ្រប់គ្រង ដើម្បីគ្រប់គ្រងកម្ចី។", "Password": "លេខសម្ងាត់", "Signing in…": "កំពុងចូល…", "Sign in": "ចូល", "Unable to sign in.": "មិនអាចចូលបាន។",
  "Portfolio": "ផលប័ត្រ", "Review every active, overdue and completed loan.": "ពិនិត្យកម្ចីកំពុងដំណើរការ ហួសកំណត់ និងបានបញ្ចប់ទាំងអស់។", "All": "ទាំងអស់", "Interest-free": "គ្មានការប្រាក់", "Active": "កំពុងដំណើរការ", "Overdue": "ហួសកំណត់", "Paid": "បានបង់", "Search borrower…": "ស្វែងរកអ្នកខ្ចី…", "Reference": "លេខយោង", "Total borrowed": "បានខ្ចីសរុប", "Next payment": "ការទូទាត់បន្ទាប់", "Status": "ស្ថានភាព", "Includes {amount} top-ups": "រួមបញ្ចូលការបន្ថែម {amount}", "Nothing here yet": "មិនទាន់មានទិន្នន័យ", "No loans match this view.": "គ្មានកម្ចីដែលត្រូវនឹងទិដ្ឋភាពនេះ។",
  "Loan management": "ការគ្រប់គ្រងកម្ចី", "Welcome to KamJey.": "សូមស្វាគមន៍មកកាន់ KamJey។", "New loan": "កម្ចីថ្មី", "Money still owed": "ប្រាក់ដែលនៅជំពាក់", "Borrowed money not yet repaid": "ប្រាក់ខ្ចីដែលមិនទាន់សង", "Interest owed": "ការប្រាក់នៅជំពាក់", "Interest already charged": "ការប្រាក់ដែលបានគិតរួច", "Total to collect": "ត្រូវប្រមូលសរុប", "Due this week": "ដល់កំណត់សប្តាហ៍នេះ", "Requires attention": "ត្រូវការយកចិត្តទុកដាក់", "Nothing due soon": "មិនមានអ្វីជិតដល់កំណត់", "Total collected": "ប្រមូលបានសរុប", "All recorded payments": "ការទូទាត់ដែលបានកត់ត្រាទាំងអស់", "Loan portfolio": "ផលប័ត្រកម្ចី", "Balances, upcoming payments and account status at a glance.": "មើលសមតុល្យ ការទូទាត់ខាងមុខ និងស្ថានភាពគណនី។", "{shown} of {total} loans": "បង្ហាញ {shown} ក្នុងចំណោម {total} កម្ចី", "Attention": "ត្រូវពិនិត្យ", "More filters": "តម្រងបន្ថែម", "All loans": "កម្ចីទាំងអស់", "Search borrower or loan ID": "ស្វែងរកអ្នកខ្ចី ឬលេខកម្ចី", "Outstanding balance": "សមតុល្យនៅសល់", "Due date": "ថ្ងៃដល់កំណត់", "Manage": "គ្រប់គ្រង", "Pay": "បង់ប្រាក់", "View history": "មើលប្រវត្តិ", "Add funds": "បន្ថែមប្រាក់", "Edit loan": "កែប្រែកម្ចី", "Delete loan": "លុបកម្ចី", "No matching loans": "គ្មានកម្ចីដែលត្រូវគ្នា", "Clear filters": "សម្អាតតម្រង", "No loans yet": "មិនទាន់មានកម្ចី", "Create your first loan": "បង្កើតកម្ចីដំបូង",
  "Due soon": "ជិតដល់កំណត់", "Paid in full": "បានបង់រួចរាល់", "{days} day(s) overdue": "ហួសកំណត់ {days} ថ្ងៃ", "Due today": "ដល់កំណត់ថ្ងៃនេះ", "Due in {days} day(s)": "ដល់កំណត់ក្នុង {days} ថ្ងៃ", "On track": "ដំណើរការល្អ", "{principal} principal · {interest} interest": "ប្រាក់ដើម {principal} · ការប្រាក់ {interest}", "Interest-free loan": "កម្ចីគ្មានការប្រាក់", "Accrued and unpaid": "បានគិត និងមិនទាន់បង់", "{rate}% · then {amount}/month": "{rate}% · បន្ទាប់មក {amount}/ខែ", "{count} recorded activities": "សកម្មភាពដែលបានកត់ត្រា {count}", "Increase this loan": "បង្កើនចំនួនកម្ចីនេះ", "Name, rate or due date": "ឈ្មោះ អត្រា ឬថ្ងៃដល់កំណត់", "Remove loan and history": "លុបកម្ចី និងប្រវត្តិ", "Try another name, loan ID, or status filter.": "សាកល្បងឈ្មោះ លេខកម្ចី ឬតម្រងស្ថានភាពផ្សេង។", "Create your first loan to begin monthly interest tracking.": "បង្កើតកម្ចីដំបូង ដើម្បីចាប់ផ្តើមតាមដានការប្រាក់ប្រចាំខែ។",
  "NEW RECORD": "កំណត់ត្រាថ្មី", "Create a loan": "បង្កើតកម្ចី", "Borrower name": "ឈ្មោះអ្នកខ្ចី", "e.g. Jamie Lee": "ឧ. សុខ ដារ៉ា", "Principal amount": "ចំនួនប្រាក់ដើម", "Monthly rate (%)": "អត្រាប្រចាំខែ (%)", "Start date": "ថ្ងៃចាប់ផ្តើម", "Choose a date": "ជ្រើសរើសកាលបរិច្ឆេទ", "Click anywhere in the field to choose a date. The first interest payment is due one month later.": "ចុចក្នុងប្រអប់ ដើម្បីជ្រើសរើសកាលបរិច្ឆេទ។ ការប្រាក់លើកដំបូងត្រូវបង់មួយខែក្រោយ។", "Create loan": "បង្កើតកម្ចី",
  "RECORD PAYMENT": "កត់ត្រាការទូទាត់", "Principal remaining": "ប្រាក់ដើមនៅសល់", "Next full-month interest": "ការប្រាក់ពេញខែបន្ទាប់", "Interest due on selected date": "ការប្រាក់ត្រូវបង់នៅថ្ងៃដែលបានជ្រើស", "Amount received": "ចំនួនប្រាក់បានទទួល", "Payment date": "ថ្ងៃទូទាត់", "Cash": "សាច់ប្រាក់", "Bank transfer": "ផ្ទេរតាមធនាគារ", "Other": "ផ្សេងៗ", "This payment": "ការទូទាត់នេះ", "To interest": "ទៅការប្រាក់", "To principal": "ទៅប្រាក់ដើម", "Principal after payment": "ប្រាក់ដើមក្រោយទូទាត់", "Interest is paid first. Only the remaining amount reduces the principal and lowers future monthly interest.": "ការប្រាក់ត្រូវបានបង់មុន។ មានតែប្រាក់នៅសល់ប៉ុណ្ណោះដែលកាត់បន្ថយប្រាក់ដើម និងការប្រាក់ប្រចាំខែនាពេលអនាគត។", "Record payment": "កត់ត្រាការទូទាត់",
  "ADD TO LOAN": "បន្ថែមទៅកម្ចី", "Principal before": "ប្រាក់ដើមមុនបន្ថែម", "Monthly rate": "អត្រាប្រចាំខែ", "Additional amount": "ចំនួនបន្ថែម", "Top-up date": "ថ្ងៃបន្ថែមប្រាក់", "Principal after top-up": "ប្រាក់ដើមក្រោយបន្ថែម", "Days charged this period": "ចំនួនថ្ងៃគិតការប្រាក់", "Interest on this top-up": "ការប្រាក់លើប្រាក់បន្ថែម", "Total interest due {date}": "ការប្រាក់សរុបត្រូវបង់ {date}", "Following full month": "ខែពេញបន្ទាប់", "Note (optional)": "កំណត់សម្គាល់ (ជាជម្រើស)", "Reason for additional borrowing": "មូលហេតុនៃការខ្ចីបន្ថែម", "Only the added amount is prorated for the remaining days. From the following full month, interest uses the complete new principal.": "មានតែប្រាក់បន្ថែមប៉ុណ្ណោះដែលគិតតាមថ្ងៃនៅសល់។ ចាប់ពីខែពេញបន្ទាប់ ការប្រាក់គិតលើប្រាក់ដើមថ្មីទាំងមូល។", "Add {amount} to loan": "បន្ថែម {amount} ទៅកម្ចី",
  "EDIT LOAN": "កែប្រែកម្ចី", "Next payment date": "ថ្ងៃទូទាត់បន្ទាប់", "Original amount: {amount}. It cannot be edited because payments are tied to it.": "ចំនួនដើម៖ {amount}។ មិនអាចកែបានទេ ព្រោះការទូទាត់ត្រូវបានភ្ជាប់ជាមួយវា។", "Saving…": "កំពុងរក្សាទុក…", "Save changes": "រក្សាទុកការកែប្រែ", "LOAN HISTORY": "ប្រវត្តិកម្ចី", "Original loan": "កម្ចីដើម", "Added funds": "ប្រាក់ដែលបានបន្ថែម", "Unpaid": "មិនទាន់បង់", "Loading history…": "កំពុងផ្ទុកប្រវត្តិ…", "No recorded payments.": "មិនមានការទូទាត់ដែលបានកត់ត្រា។", "Top-ups": "ការបន្ថែមប្រាក់", "Added": "បានបន្ថែម", "Prorated interest": "ការប្រាក់គិតតាមថ្ងៃ", "Before": "មុន", "After": "ក្រោយ", "No top-ups recorded.": "មិនមានការបន្ថែមប្រាក់ដែលបានកត់ត្រា។", "Delete {borrower}'s loan and all of its payment history? This cannot be undone.": "លុបកម្ចីរបស់ {borrower} និងប្រវត្តិទូទាត់ទាំងអស់មែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។",
  "Outstanding breakdown": "សមាសភាពប្រាក់នៅសល់", "Principal vs. interest still to collect": "ប្រាក់ដើម និងការប្រាក់ដែលត្រូវប្រមូល", "Total outstanding": "ប្រាក់នៅសល់សរុប", "Money owed to you": "ប្រាក់ដែលគេជំពាក់អ្នក", "Principal and unpaid interest across your portfolio.": "ប្រាក់ដើម និងការប្រាក់មិនទាន់បង់ក្នុងផលប័ត្ររបស់អ្នក។", "Total receivable": "ប្រាក់ត្រូវទទួលសរុប", "Principal outstanding": "ប្រាក់ដើមនៅសល់", "Unpaid interest": "ការប្រាក់មិនទាន់បង់", "Money to collect": "ប្រាក់ត្រូវប្រមូល", "What borrowers still need to pay.": "ប្រាក់ដែលអ្នកខ្ចីនៅត្រូវបង់។", "Total": "សរុប", "Interest left this month": "ការប្រាក់នៅសល់ខែនេះ", "Expected monthly interest": "ការប្រាក់រំពឹងប្រចាំខែ", "Based on current balances": "ផ្អែកលើសមតុល្យបច្ចុប្បន្ន", "Received this month": "បានទទួលក្នុងខែនេះ", "Loan status": "ស្ថានភាពកម្ចី", "Current portfolio health": "ស្ថានភាពផលប័ត្របច្ចុប្បន្ន", "Total loans": "កម្ចីសរុប", "Active loans": "កម្ចីកំពុងដំណើរការ", "Across {count} borrowers": "ក្នុងចំណោមអ្នកខ្ចី {count} នាក់", "Needs attention": "ត្រូវការយកចិត្តទុកដាក់", "Portfolio is clear": "ផលប័ត្រមិនមានបញ្ហា", "Collected to date": "បានប្រមូលរហូតមកដល់បច្ចុប្បន្ន", "Across all recorded payments": "ក្នុងការទូទាត់ដែលបានកត់ត្រាទាំងអស់", "No data": "គ្មានទិន្នន័យ",
  "Actions": "សកម្មភាព", "Edit": "កែប្រែ", "Delete": "លុប", "Locked": "បានចាក់សោ", "EDIT ADDED FUNDS": "កែប្រែប្រាក់បន្ថែម", "The loan principal and prorated interest will be recalculated automatically.": "ប្រាក់ដើម និងការប្រាក់គិតតាមថ្ងៃនឹងត្រូវគណនាឡើងវិញដោយស្វ័យប្រវត្តិ។", "Delete this added-funds record? The loan balance and interest will be recalculated.": "លុបកំណត់ត្រាប្រាក់បន្ថែមនេះមែនទេ? សមតុល្យកម្ចី និងការប្រាក់នឹងត្រូវគណនាឡើងវិញ។",
  "Changing the amount or rate recalculates principal and interest. Financial terms are locked after payments, added funds, or accrued interest exist.": "ការផ្លាស់ប្តូរចំនួនប្រាក់ ឬអត្រា នឹងគណនាប្រាក់ដើម និងការប្រាក់ឡើងវិញ។ លក្ខខណ្ឌហិរញ្ញវត្ថុនឹងត្រូវចាក់សោ បន្ទាប់ពីមានការទូទាត់ ប្រាក់បន្ថែម ឬការប្រាក់ដែលបានគិត។",
  "Changing the amount or rate recalculates principal and accrued interest. Financial terms are locked after payments or added funds exist.": "ការផ្លាស់ប្តូរចំនួនប្រាក់ ឬអត្រា នឹងគណនាប្រាក់ដើម និងការប្រាក់ដែលបានគិតឡើងវិញ។ លក្ខខណ្ឌហិរញ្ញវត្ថុនឹងត្រូវចាក់សោ បន្ទាប់ពីមានការទូទាត់ ឬប្រាក់បន្ថែម។",
  "Current": "បានបង់បច្ចុប្បន្ន", "Not due yet": "មិនទាន់ដល់កំណត់", "No scheduled payment": "មិនមានការទូទាត់កំណត់ពេល", "Principal payment": "ការទូទាត់ប្រាក់ដើម", "Paid off": "បានសងរួចរាល់", "Next interest": "ការប្រាក់បន្ទាប់", "Next interest: {amount} · {rate}%": "ការប្រាក់បន្ទាប់៖ {amount} · {rate}%", "Interest paid; nothing is currently due": "បានបង់ការប្រាក់រួច មិនមានប្រាក់ត្រូវបង់ឥឡូវនេះ", "Payment status": "ស្ថានភាពទូទាត់",
  "Paid this cycle": "បានបង់វគ្គនេះ", "Paid this month": "បានបង់ក្នុងខែនេះ", "Paid {amount} this cycle · next {next}": "បានបង់ {amount} វគ្គនេះ · បន្ទាប់ {next}",
  "{principal} principal · {interest} current interest": "ប្រាក់ដើម {principal} · ការប្រាក់បច្ចុប្បន្ន {interest}", "Paid {amount} for {month}": "បានបង់ {amount} សម្រាប់ខែ {month}", "Interest paid": "បានបង់ការប្រាក់", "{amount} paid": "បានបង់ {amount}", "Paid {amount}": "បានបង់ {amount}", "on {date}": "នៅថ្ងៃទី {date}", "{amount} interest": "ការប្រាក់ {amount}", "Last paid on {date}": "បានបង់ចុងក្រោយនៅថ្ងៃទី {date}",
  "{amount} principal": "ប្រាក់ដើម {amount}", "Next interest payment": "ត្រូវទូទាត់ខែបន្ទាប់",
};

type ContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string, variables?: Variables) => string; locale: string };
const LanguageContext = createContext<ContextValue | null>(null);

const languageEvent = "kamjey-language-change";
const serverLanguage = (): Language => "en";
const browserLanguage = (): Language => localStorage.getItem("kamjey-language") === "km" ? "km" : "en";
const subscribeToLanguage = (notify: () => void) => {
  window.addEventListener("storage", notify);
  window.addEventListener(languageEvent, notify);
  return () => {
    window.removeEventListener("storage", notify);
    window.removeEventListener(languageEvent, notify);
  };
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const language = useSyncExternalStore(subscribeToLanguage, browserLanguage, serverLanguage);
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dataset.language = language; }, [language]);
  const setLanguage = (next: Language) => { localStorage.setItem("kamjey-language", next); window.dispatchEvent(new Event(languageEvent)); };
  const t = (key: string, variables: Variables = {}) => { let result = language === "km" ? km[key] ?? key : key; for (const [name, value] of Object.entries(variables)) result = result.replaceAll(`{${name}}`, String(value)); return result; };
  return <LanguageContext.Provider value={{ language, setLanguage, t, locale: language === "km" ? "km-KH" : "en-US" }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error("useLanguage must be used inside LanguageProvider"); return value; }
export function LanguageSwitcher() { const { language, setLanguage, t } = useLanguage(); return <div className="language-switcher" role="group" aria-label={t("Language")}><button type="button" className={language === "en" ? "active" : ""} onClick={() => setLanguage("en")} aria-label="English" title="English"><Image src="/flag-english.svg" alt="" width={36} height={22} priority /></button><button type="button" className={language === "km" ? "active" : ""} onClick={() => setLanguage("km")} aria-label="ភាសាខ្មែរ" title="ភាសាខ្មែរ"><Image src="/flag-khmer.svg" alt="" width={36} height={22} priority /></button></div>; }
