"use client";

import { useEffect, useState } from "react";

type Settings = { general: { currency: string; dateFormat: string; interestModel: string }; integrations: { telegram: boolean; adminChat: boolean; reminders: boolean }; security: { hashedPassword: boolean; sessionSecret: boolean; plaintextPassword: boolean } };

export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/settings").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); return body; }).then(setSettings).catch((reason: Error) => setError(reason.message)); }, []);
  return <main className="route-page settings-page"><header className="route-header"><div><p className="eyebrow">Configuration</p><h1>Settings</h1><p>Review application conventions, integrations, security and data tools.</p></div></header>{error && <p className="database-notice">{error}</p>}{settings ? <div className="settings-grid"><SettingsCard title="General" copy="Current financial display and calculation conventions."><SettingRow label="Currency" value={settings.general.currency}/><SettingRow label="Date format" value={settings.general.dateFormat}/><SettingRow label="Interest model" value={settings.general.interestModel}/></SettingsCard><SettingsCard title="Telegram reminders" copy="Secrets remain protected on the server; only their status is shown."><StatusRow label="Bot token" ready={settings.integrations.telegram}/><StatusRow label="Admin chat" ready={settings.integrations.adminChat}/><StatusRow label="Cron protection" ready={settings.integrations.reminders}/></SettingsCard><SettingsCard title="Security" copy="Authentication configuration loaded from the deployment environment."><StatusRow label="Password hash" ready={settings.security.hashedPassword}/><StatusRow label="Session signing" ready={settings.security.sessionSecret}/>{settings.security.plaintextPassword && <div className="settings-warning"><strong>Plaintext password enabled</strong><p>Remove ADMIN_PASSWORD after confirming the password hash works.</p></div>}</SettingsCard><SettingsCard title="Data" copy="Download a portable snapshot of current operational records."><a className="export-button" href="/api/export" download>↓ Export loans and payments</a><p className="settings-help">The JSON export includes borrowers, loans and payment history. Store it securely.</p></SettingsCard></div> : <p className="settings-loading">Loading settings…</p>}</main>;
}

function SettingsCard({ title, copy, children }: { title: string; copy: string; children: React.ReactNode }) { return <section className="settings-card"><h2>{title}</h2><p>{copy}</p><div className="settings-rows">{children}</div></section>; }
function SettingRow({ label, value }: { label: string; value: string }) { return <div className="setting-row"><span>{label}</span><strong>{value}</strong></div>; }
function StatusRow({ label, ready }: { label: string; ready: boolean }) { return <div className="setting-row"><span>{label}</span><strong className={ready ? "config-ready" : "config-missing"}>{ready ? "Configured" : "Missing"}</strong></div>; }
